### PR TITLE
Update controller.php

### PR DESCRIPTION
**Pull request by a3020**
Typos

### CODE REVIEW

**Comment by tkart38** [comment]
hi
 what do you think about add on tutorial how to make a new attribute type ?
with the basic function. 
if possible how to add an attribute type like the address with some child.

**Comment by tkart38** [comment]
hi 
what do you think about add on tutorial how to make a new attribute type?
with the basic function required?
and if possible with the example of a type with some child like the address
 thanks

**Comment by cryophallion** [comment]
I have NO idea why I didn't see this until now. My apologies, and I'm merging in.

**Comment by cryophallion** [comment]
@tkart38 I had an attribute type tutorial up on the documentation page. Is that what you are asking about?

**Comment by tkart38** [comment]
hi
yes thanks!
i've whorked on it and on  this https://github.com/Remo/concrete5-attribute-multi-text

I made a package for do an attribute type with multiple text field. (like address but simplfied)
now i can set programmatically an attribute whit an array of value.
thanks

**Pull request merged**
